pipeline {
    agent any
    environment {
        DOCKER_IMAGE = 'nextjs-app'
        DOCKER_REGISTRY = 'https://hub.docker.com/r/prasadmpotdar'
        K8S_NAMESPACE = 'default'
        K8S_DEPLOYMENT_NAME = 'nextjs-app-deployment'
        FULL_IMAGE_NAME = "${DOCKER_REGISTRY}/${DOCKER_IMAGE}"
    }
    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/prasad-potdar/nextjs-docker-jenkins-cicd-deployment-test.git'
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    // Build Docker image
                     sh "docker build -t ${FULL_IMAGE_NAME}:${env.BUILD_NUMBER} ."
                }
            }
        }
        stage('Push Docker Image to Registry') {
            steps {
                script {
                    // Log into Docker registry
                    withCredentials([string(credentialsId: 'docker-hub-access-token', variable: 'DOCKER_ACCESS_TOKEN')]) {
                        // Login to Docker Hub
                        sh """
                        echo $DOCKER_ACCESS_TOKEN | docker login -u $REGISTRY_HOST --password-stdin
                        """

                        // Build and push Docker image
                        sh """
                        docker build -t ${FULL_IMAGE_NAME}:${env.BUILD_NUMBER} -f deployment/Dockerfile .
                        docker tag ${FULL_IMAGE_NAME}:${env.BUILD_NUMBER} ${FULL_IMAGE_NAME}:latest
                        docker push ${FULL_IMAGE_NAME}:${env.BUILD_NUMBER}
                        docker push ${FULL_IMAGE_NAME}:latest
                        """
                    }
                }
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                script {
                    // Deploy Docker image to Kubernetes
                    sh """
                        kubectl set image deployment/$K8S_DEPLOYMENT_NAME nextjs-app=$DOCKER_REGISTRY/$DOCKER_IMAGE --namespace=$K8S_NAMESPACE
                    """
                }
            }
        }
    }
}
