apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-app
  labels:
    app: nextjs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs-app
  template:
    metadata:
      labels:
        app: nextjs-app
    spec:
      containers:
        - name: nextjs-app
          image: <IMAGE_TAG> # Replace <IMAGE_TAG> with your image name (e.g., myrepo/nextjs-app:latest)
          ports:
            - containerPort: 3001
          env:
            - name: NEXT_DISABLE_ESLINT
              value: "true" # Disables ESLint during build
            - name: BUILD_NUMBER
              value: "1" # Example environment variable
