apiVersion: v1
kind: Service
metadata:
  name: nextjs-app-service
spec:
  selector:
    app: nextjs-app
  ports:
    - protocol: TCP
      port: 80        # Expose on this port
      targetPort: 3001 # Container's internal port
      nodePort: 30081  # Assign a port on the node for external access
  type: NodePort  # Expose the service via NodePort
