apiVersion: v1
kind: Service
metadata:
  name: nextjs-app-service
  labels:
    app: nextjs-app
spec:
  selector:
    app: nextjs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: NodePort
